"""Added more info fields to the song model

Revision ID: 2dcb0e48d7a8
Revises: c6498877d01a
Create Date: 2025-06-29 22:02:04.776901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcb0e48d7a8'
down_revision = 'c6498877d01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('album', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.drop_column('album')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###
