"""Switched dmx scenes to use song id insteasd of song name

Revision ID: 3533f9938b89
Revises: e7b5201eceb8
Create Date: 2025-09-09 21:00:53.137518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3533f9938b89'
down_revision = 'e7b5201eceb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dmxscene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_dmxscene_song_id_songs_id', 'Songs', ['song_id'], ['id'])
        batch_op.drop_column('song_keybind')
        batch_op.drop_column('updateDate')
        batch_op.drop_column('createDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dmxscene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createDate', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updateDate', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('song_keybind', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_constraint('fk_dmxscene_song_id_songs_id', type_='foreignkey')
        batch_op.drop_column('song_id')
        batch_op.drop_column('create_date')
        batch_op.drop_column('update_date')
    # ### end Alembic commands ###
