"""AddedYoutubeLinkToSongModel

Revision ID: 35ac0b552869
Revises: 9bfd2179ea31
Create Date: 2025-06-12 23:35:16.092129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ac0b552869'
down_revision = '9bfd2179ea31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtubeLink', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.drop_column('youtubeLink')

    # ### end Alembic commands ###
