"""RemoveRequestIdFromFeedbackModels

Revision ID: 3dc6a3009fa3
Revises: 284ca09c82e0
Create Date: 2025-05-13 22:10:37.627582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc6a3009fa3'
down_revision = '284ca09c82e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BugReports', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    with op.batch_alter_table('NewFeatureRequests', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    with op.batch_alter_table('SongRequests', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SongRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('NewFeatureRequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('BugReports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
