"""Add BPM to song models

Revision ID: 6427cc066371
Revises: 38a252bd4406
Create Date: 2025-08-03 00:37:25.188395

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6427cc066371'
down_revision = '38a252bd4406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bpm', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.drop_column('bpm')

    # ### end Alembic commands ###
