"""AddGameEventKeybinds

Revision ID: 66ed9192bcac
Revises: 3533f9938b89
Create Date: 2025-09-14 17:00:09.879926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ed9192bcac'
down_revision = '3533f9938b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameEventType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dmxscene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("GameEventType_Id", 'gameEventType', ['game_event_id'], ['id'])
        batch_op.drop_column('game_event_keybind')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dmxscene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_event_keybind', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('game_event_id')

    op.drop_table('gameEventType')
    # ### end Alembic commands ###
