"""Initial DB Creation

Revision ID: c80e35d97907
Revises: 
Create Date: 2025-02-27 08:53:48.329273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80e35d97907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmxscene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('updateDate', sa.DateTime(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('flash', sa.Boolean(), nullable=False),
    sa.Column('keyboard_keybind', sa.String(length=15), nullable=True),
    sa.Column('song_keybind', sa.String(length=15), nullable=True),
    sa.Column('game_event_keybind', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('noOfchannels', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('defaultColor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('internal_server_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_message', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('gamesWon', sa.Integer(), nullable=False),
    sa.Column('gamesLost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('teamColour', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dmxsceneevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sceneID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('updateDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sceneID'], ['dmxscene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixturechannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixtureID', sa.Integer(), nullable=False),
    sa.Column('channelNo', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fixtureID'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('winningPlayerRed', sa.Integer(), nullable=True),
    sa.Column('winningPlayerGreen', sa.Integer(), nullable=True),
    sa.Column('winningPlayer', sa.Integer(), nullable=True),
    sa.Column('winningTeam', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winningPlayer'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winningPlayerGreen'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winningPlayerRed'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winningTeam'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dmx_scene_event_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('fixture', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['dmxsceneevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixturechannelvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelID', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['channelID'], ['fixturechannel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('gunID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('playerWon', sa.Boolean(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameID'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gunID'], ['gun.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_players')
    op.drop_table('fixturechannelvalue')
    op.drop_table('dmx_scene_event_channel')
    op.drop_table('game')
    op.drop_table('fixturechannel')
    op.drop_table('dmxsceneevent')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('internal_server_error')
    op.drop_table('gun')
    op.drop_table('fixture')
    op.drop_table('dmxscene')
    # ### end Alembic commands ###
