"""Add Patched Fixture Group Model

Revision ID: e5b145c18ac9
Revises: 15ca909e4cd1
Create Date: 2025-05-17 21:42:26.505210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b145c18ac9'
down_revision = '15ca909e4cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patchedfixturegroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(length=100), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patchedfixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_patchedfixtures_group_id', 'patchedfixturegroups', ['groupId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patchedfixtures', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patchedfixtures_group_id', type_='foreignkey')
        batch_op.drop_column('groupId')

    op.drop_table('patchedfixturegroups')
    # ### end Alembic commands ###
