"""Add patched fixture model

Revision ID: 15ca909e4cd1
Revises: a4181b8c1624
Create Date: 2025-05-17 21:29:26.170206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ca909e4cd1'
down_revision = 'a4181b8c1624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patchedfixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixtureId', sa.Integer(), nullable=False),
    sa.Column('dmxControllerFixtureId', sa.Integer(), nullable=False),
    sa.Column('dmxStartAddress', sa.Integer(), nullable=False),
    sa.Column('dmxEndAddress', sa.Integer(), nullable=False),
    sa.Column('fixtureName', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fixtureId'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patchedfixtures')
    # ### end Alembic commands ###
