"""UpdateDashboardTables

Revision ID: 1c3830e281c1
Revises: 14d847f8ab15
Create Date: 2025-05-28 23:55:17.172707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3830e281c1'
down_revision = '14d847f8ab15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardCategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=False))

    with op.batch_alter_table('DashboardWidgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DashboardWidgets', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    with op.batch_alter_table('DashboardCategories', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
