"""AddingFormSubmissionModels

Revision ID: 2328c6175ea3
Revises: 74f05a9f30ed
Create Date: 2025-04-26 23:45:57.259027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2328c6175ea3'
down_revision = '74f05a9f30ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BugReports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('when_occurs', sa.String(length=255), nullable=False),
    sa.Column('expected_behavior', sa.String(length=255), nullable=False),
    sa.Column('steps_to_reproduce', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('submitter_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('NewFeatureRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('use_case', sa.String(length=255), nullable=False),
    sa.Column('expected', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('submitter_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('SongRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(length=255), nullable=False),
    sa.Column('naughty_words', sa.Boolean(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('submitter_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SongRequests')
    op.drop_table('NewFeatureRequests')
    op.drop_table('BugReports')
    # ### end Alembic commands ###
