"""Add Restart Request model

Revision ID: 284ca09c82e0
Revises: 2328c6175ea3
Create Date: 2025-05-04 23:00:55.317148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284ca09c82e0'
down_revision = '2328c6175ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RestartRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('created_by_service_name', sa.String(length=255), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RestartRequests')
    # ### end Alembic commands ###
