"""Add Playlist Models

Revision ID: 33091af3ed64
Revises: 1c3830e281c1
Create Date: 2025-06-09 23:33:46.030555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33091af3ed64'
down_revision = '1c3830e281c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlistSongs',
    sa.Column('playlistId', sa.Integer(), nullable=False),
    sa.Column('songId', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['playlistId'], ['Playlists.id'], ),
    sa.ForeignKeyConstraint(['songId'], ['Songs.id'], ),
    sa.PrimaryKeyConstraint('playlistId', 'songId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlistSongs')
    op.drop_table('Songs')
    op.drop_table('Playlists')
    # ### end Alembic commands ###
