"""Adding account models

Revision ID: 38a252bd4406
Revises: 0766c33f821c
Create Date: 2025-08-02 23:04:28.269162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '38a252bd4406'
down_revision = '0766c33f821c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=200), nullable=False),
        sa.Column('password', sa.String(length=200), nullable=False),
        sa.Column('createDate', sa.DateTime(), nullable=False),
        sa.Column('isActive', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserAuthTokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('userId', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=200), nullable=False),
        sa.Column('expiryDate', sa.DateTime(), nullable=False),
        sa.Column('createDate', sa.DateTime(), nullable=False),
        sa.Column('isActive', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAuthTokens')
    op.drop_table('Users')
    # ### end Alembic commands ###
