"""ChangingTheNamesOfSomeColumns

Revision ID: 3b4ff9b5f8bb
Revises: 33091af3ed64
Create Date: 2025-06-11 23:07:39.555484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4ff9b5f8bb'
down_revision = '33091af3ed64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlistSongs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('playlistId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('songId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlistSongs', schema=None) as batch_op:
        batch_op.alter_column('songId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('playlistId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
