"""Update player models

Revision ID: 5342edb16084
Revises: 5f4f469c7ac7
Create Date: 2025-03-07 22:11:51.549078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5342edb16084'
down_revision = '5f4f469c7ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('gunID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=True),
    sa.Column('playerWon', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameID'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gunID'], ['gun.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gameID', sa.INTEGER(), nullable=False),
    sa.Column('gunID', sa.INTEGER(), nullable=False),
    sa.Column('playerID', sa.INTEGER(), nullable=False),
    sa.Column('playerWon', sa.BOOLEAN(), nullable=False),
    sa.Column('team', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gameID'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gunID'], ['gun.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_player')
    # ### end Alembic commands ###
