"""Add Home Page preset models

Revision ID: 5f4f469c7ac7
Revises: 99d93fc2cf3f
Create Date: 2025-03-04 22:54:13.461232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4f469c7ac7'
down_revision = '99d93fc2cf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customhomescreenpreset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presetcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('homeScreenPresetId', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['homeScreenPresetId'], ['customhomescreenpreset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presetcard')
    op.drop_table('customhomescreenpreset')
    # ### end Alembic commands ###
