"""Add DMX Channel Patch Table

Revision ID: 99d93fc2cf3f
Revises: c80e35d97907
Create Date: 2025-03-03 23:49:28.000937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d93fc2cf3f'
down_revision = 'c80e35d97907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmxpatchedchannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelId', sa.Integer(), nullable=True),
    sa.Column('fixtureChannelID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixtureChannelID'], ['fixturechannel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dmxpatchedchannel')
    # ### end Alembic commands ###
