"""ChangeNaughtyWordsToString

Revision ID: a4181b8c1624
Revises: 3dc6a3009fa3
Create Date: 2025-05-13 22:17:13.701069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4181b8c1624'
down_revision = '3dc6a3009fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SongRequests', schema=None) as batch_op:
        batch_op.alter_column('naughty_words',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SongRequests', schema=None) as batch_op:
        batch_op.alter_column('naughty_words',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
