"""UpdatingIdColumns

Revision ID: ac839aaf46ac
Revises: 3b4ff9b5f8bb
Create Date: 2025-06-12 00:00:45.479280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac839aaf46ac'
down_revision = '3b4ff9b5f8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlistSongs', schema=None) as batch_op:
        batch_op.alter_column('playlistId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('songId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlistSongs', schema=None) as batch_op:
        batch_op.alter_column('songId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('playlistId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
