"""AddingIsDownloadedBoolToSongModel

Revision ID: c6498877d01a
Revises: 35ac0b552869
Create Date: 2025-06-15 13:07:32.541445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6498877d01a'
down_revision = '35ac0b552869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDownloaded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.drop_column('isDownloaded')

    # ### end Alembic commands ###
