"""Add BPM to song models

Revision ID: d1b838d8bd1f
Revises: 6427cc066371
Create Date: 2025-08-05 22:53:28.141458

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1b838d8bd1f'
down_revision = '6427cc066371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.alter_column('bpm',
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Songs', schema=None) as batch_op:
        batch_op.alter_column('bpm',
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True)

    # ### end Alembic commands ###
