"""Adding user permission

Revision ID: e7b5201eceb8
Revises: d1b838d8bd1f
Create Date: 2025-08-09 23:37:34.317364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b5201eceb8'
down_revision = 'd1b838d8bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserPermissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('permissionId', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPermissions')
    op.drop_table('Permissions')
    # ### end Alembic commands ###
